name: auto_deploy_test


on:
  push:
    branches:
    - test
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
