name: auto_deploy_test


on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          path: ./1/2/3/4
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: ls1
        run: |
          ls
          pwd
      - name: Install Dependencies
        run: |
          sudo apt-get install python3-pip
          pip3 install --upgrade pip
          pip3 install -r ./requirements.txt
      - name: ls
        run: |
          ls
      - name: cd
        run: |
          cd ./1/2
